using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;

namespace SCSM.Data.Respositories
{
   public class PreviousMonthSalesRepository : BaseRespository
    {

        //calculate how much revenue was generated by getting the price and units sold from last month and multiplying then
        public double GenerateRevenue(string itemCode)
        {
            
            using (var conn = new MySqlConnection(GenerateConnectionString()))
            {
                conn.Open();
                using (var cmd = new MySqlCommand("SELECT * FROM previous_month_sales where item_code = @item_code", conn))
                {
                    cmd.Parameters.AddWithValue("@item_code", itemCode);
                    MySqlDataReader rdr = cmd.ExecuteReader();
                    while (rdr.Read())
                    {
                        var price=(double)rdr["price"];
                        var unitsSold = (int)rdr["units_sold"];


                        var revenue = price * Convert.ToDouble(unitsSold);

                        
                        return revenue;
                    }
                }
                return 0;
            }
        }

    }
}
